name: Build and Deploy to Google Cloud Storage

on:
  push:
    branches:
    - develop


env:
  GCS_BUCKET: gs://jar-files-pfe/

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup - gcloud / gsutil
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.KEY_FILE_GCP }}
          project_id: pfe-data-finnhub
          export_default_credentials: true


      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Change Dir and Build Fat Jar
        run: cd scala/projetv0 && sbt assembly
      - name: Change Dir
        run: cd scala/projetv0/target/scala-2.12 && ls

      - id: upload-file
        uses: google-github-actions/upload-cloud-storage@main
        with:
          credentials: ${{ secrets.KEY_FILE_GCP }}
          path: scala/projetv0/target/scala-2.12/projetv0-assembly-0.1.jar
          destination: jar-files-pfe/projetv0-assembly-0.1.jar



